
/**
 * @author MELISSA LIAO
 *
 */
public class RandomThreadApp {
	
	public static void main(String args[]) {
		int min = 1;
		int max = 100;
		
		// One instantiation of randomizer to store
		// multiple random numbers
		Randomizer r = new Randomizer(min, max);
		
		// 5 different threads will run the same
		// Randomizer class to generate a random number
		Thread t1 = new Thread(r);
		Thread t2 = new Thread(r);
		Thread t3 = new Thread(r);
		Thread t4 = new Thread(r);
		Thread t5 = new Thread(r);
		
		t1.start();
		t2.start();
		t3.start();
		t4.start();
		t5.start();
		
		try { // Join function is called in to run all threads first
			t1.join();
			t2.join();
			t3.join();
			t4.join();
			t5.join();
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
		// After all threads had finished running, main thread will print out 
		// all random values stored from ArrayList in Randomizer class
		System.out.println("\nValues generated by all 5 threads: ");
		for(Integer rand: r.getValue())
			System.out.print(rand + "  ");
		
		// Call in the sum variable to retrieve the sum all generated random values
		System.out.println("\nSum of random numbers = " + r.getSum());
		

	}

}
