
/**
 * @author MELISSA LIAO
 *
 */
public class RandomThreadApp {
	
	public static void main(String args[]) {
		int min = 1;
		int max = 100;
		
		// Instantiate 5 different randomizers to
		// generate 5 different random numbers
		Randomizer r1 = new Randomizer(min, max);
		Randomizer r2 = new Randomizer(min, max);
		Randomizer r3 = new Randomizer(min, max);
		Randomizer r4 = new Randomizer(min, max);
		Randomizer r5 = new Randomizer(min, max);
		
		// Each generated random number will be run
		// by its own thread
		Thread t1 = new Thread(r1);
		Thread t2 = new Thread(r2);
		Thread t3 = new Thread(r3);
		Thread t4 = new Thread(r4);
		Thread t5 = new Thread(r5);
		
		t1.start();
		t2.start();
		t3.start();
		t4.start();
		t5.start();
		
		try { // Join function is called in to run all threads first
			t1.join();
			t2.join();
			t3.join();
			t4.join();
			t5.join();
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
		
		// After all threads had finished running, main thread will print out all random values
		// stored in object from Randomizer class
		System.out.println("Random number generated by " + t1.getName() + ": "+ r1.getValue());
		System.out.println("Random number generated by " + t2.getName() + ": "+ r2.getValue());
		System.out.println("Random number generated by " + t3.getName() + ": "+ r3.getValue());
		System.out.println("Random number generated by " + t4.getName() + ": "+ r4.getValue());
		System.out.println("Random number generated by " + t5.getName() + ": "+ r5.getValue());
		
		// Each random number stored from single object will be called in from each randomizer
		// to get the sum of the values
		int sum = r1.getValue() + r2.getValue() + r3.getValue() + r4.getValue() + r5.getValue();
		System.out.println("Sum of random numbers = " + sum);
		

	}

}
